apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-prod-etherpad.yaml
  - persistentvolumeclaim-prod-etherpad.yaml
  - route-prod-etherpad.yaml
  - service-prod-etherpad.yaml
